version: '3'
services:
        web:
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                ports:
                        - "3000:3000"
                volumes:
                        - /app/node_modules
                        - .:/app
# this is for instead running long command docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app -d sri596/reactsample:1
# we are writing this file
